<?php

return [


    'GURUCOMI_DOMAIN' => "funse.net",
    'GURUCOMI_ALIAS' => "gurucomi",


    'PLACE_TYPES' => [
        "accounting" => "会計事務所",
        "Otolaryngologist" => "耳鼻科",
        "airport" => "空港",
        "amusement_park" => "遊園地",
        "aquarium" => "水族館",
        "art_gallery" => "美術館",
        "atm" => "ATM",
        "bank" => "銀行",
        "beauty_salon" => "美容室",
        "bicycle_store" => "自転車屋",
        "book_store" => "書店",
        "bowling_alley" => "ボウリング場",
        "bus_station" => "バス停",
        "cafe" => "カフェ",
        "campground" => "キャンプ場",
        "car_dealer" => "自動車ディーラー",
        "car_rental" => "レンタカー",
        "car_repair" => "自動車修理",
        "car_wash" => "洗車",
        "casino" => "カジノ",
        "cemetery" => "墓地",
        "church" => "教会",
        "city_hall" => "市役所",
        "clothing_store" => "衣料品",
        "convenience_store" => "コンビニ",
        "courthouse" => "裁判所",
        "dentist" => "歯科",
        "department_store" => "デパート",
        "doctor" => "医者",
        "electrician" => "電気事業者",
        "electronics_store" => "家電",
        "embassy" => "大使館",
        "finance" => "財務機関",
        "fire_station" => "消防署",
        "florist" => "花",
        "food" => "グルメ",
        "funeral_home" => "葬祭",
        "furniture_store" => "家具",
        "gas_station" => "ガソリンスタンド",
        "general_contractor" => "ゼネコン",
        "grocery_or_supermarket" => "スーパー",
        "gym" => "スポーツジム",
        "hair_care" => "美容院",
        "hardware_store" => "ホームセンター",
        "health" => "医療機関",
        "hindu_temple" => "寺院",
        "home_goods_store" => "ホームセンター",
        "hospital" => "医療機関",
        "insurance_agency" => "保険代理店",
        "jewelry_store" => "宝石",
        "laundry" => "クリーニング",
        "lawyer" => "法律事務所",
        "library" => "図書館",
        "liquor_store" => "酒",
        "local_government_office" => "役所",
        "locksmith" => "鍵屋",
        "lodging" => "宿泊施設",
        "meal_delivery" => "飲食出前",
        "meal_takeaway" => "飲食テイクアウト",
        "mosque" => "モスク",
        "movie_rental" => "ビデオレンタル",
        "movie_theater" => "映画館",
        "moving_company" => "引越し",
        "night_club" => "ナイトクラブ",
        "painter" => "塗装",
        "park" => "公園",
        "pet_store" => "ペット",
        "pharmacy" => "薬局",
        "physiotherapist" => "療法士",
        "place_of_worship" => "神社・寺",
        "plumber" => "配管工",
        "police" => "警察",
        "post_office" => "郵便局",
        "real_estate_agency" => "不動産",
        "restaurant" => "レストラン",
        "roofing_contractor" => "屋根",
        "rv_park" => "RVパーク",
        "school" => "学校, 塾",
        "shoe_store" => "靴",
        "shopping_mall" => "ショッピングモール",
        "spa" => "温泉",
        "stadium" => "スタジアム",
        "storage" => "倉庫",
        "subway_station" => "鉄道駅",
        "synagogue" => "シナゴーグ",
        "taxi_stand" => "タクシー",
        "train_station" => "鉄道駅",
        "travel_agency" => "旅行代理店",
        "university" => "大学",
        "veterinary_care" => "動物病院",
        "zoo" => "動物園",
        "Day Hot Spring" => "日帰り温泉",
        "Fishing Store" => "釣具店",
        "Live Music Venue" => "ライブ会場",
        "Blood Bank" => "血液センター",
        "Motorcycle Dealer" => "バイク販売",
        "Ferry Service" => "フェリー",
        "Archaeological Museum" => "考古学博物館",
        "Bridge" => "橋",
        "Railroad Company" => "駅",
        "Used Car Dealer" => "中古車",
        "Japanized Western Restaurant" => "日本式洋食",
        "Concert Hall" => "コンサート ホール",
        "Health Spa" => "健康ランド",
        "Box Lunch Supplier" => "弁当",
        "hospital" => "医療機関",
        "Portrait Studio" => "写真館",
        "Auto Parts Store" => "自動車用品",
        "Senior High School" => "高等学校",
        "Public University" => "公立大学",
        "Hair Salon" => "美容院",
        "Optician" => "メガネ",
        "District Government Office" => "地区庁舎",
        "Hairdresser" => "理容院",
        "Manufacturer" => "製造",
        "Suzuki Dealer" => "スズキ販売",
        "Natural Stone Supplier" => "天然石",
        "Sporting Goods Store" => "スポーツ用品",
        "Gymnastics Center" => "競技場",
        "veterinary_care" => "動物病院",
        "Buddhist Temple" => "仏教寺院",
        "Shinto Shrine" => "神社",
        "Nursery School" => "保育園",
        "Elementary School" => "小学校",
        "Local Bank" => "地方銀行",
        "Internist" => "内科医",
        "Kindergarten" => "幼稚園",
        "Pachinko Parlor" => "パチンコ",
        "Middle School" => "中学校",
        "University" => "大学",
        "Coin Parking" => "コインパーキング",
        "Propane Supplier" => "燃料",
        "Shinkin Bank" => "信金",
        "Corporate Office" => "会社",
        "Association or Organization" => "協会",
        "Rice Shop" => "米",
        "Sign Shop" => "看板",
        "Orthopedic Surgeon" => "整形外科",
        "Landscaping Supply Store" => "造園",
        "Wholesaler" => "卸売",
        "Tire Shop" => "タイヤ",
        "Women's Clothing Store" => "婦人服",
        "Assisted Living Facility" => "介護住宅",
        "Stationery Store" => "文房具",
        "Lumber Store" => "材木",
        "Cramming School" => "予備校",
        "home_goods_store" => "ふとん",
        "Dermatologist" => "皮膚科",
        "Obstetrician-Gynecologist" => "産婦人科",
        "Ophthalmologist" => "眼科",
        "Natural Foods Store" => "自然食品",
        "Musical Instrument Store" => "楽器",
        "General Hospital" => "総合病院",
        "Recycling Center" => "廃品リサイクル",
        "Government Office" => "政府",
        "Pediatrician" => "小児科",
        "Pediatrician" => "私立大学",
        "Wedding Venue" => "結婚式場",
        "Costume Rental Service" => "衣装レンタル",
        "Urologist" => "泌尿器科",
        "Ranch" => "牧場",
        "Tropical Fish Store" => "熱帯魚",
        "Metalworking" => "金属加工業",
        "Logistics Service" => "流通",
        "Dry Goods Store" => "呉服",
        "Taxi Service" => "タクシー",
        "Company" => "会社",
        "Chemical Industry" => "化学産業",
        "Adult Day Care Center" => "デイケアサービス",
        "Tennis Court" => "テニスコート",
        "Tea Store" => "お茶販売",
        "Discount Store" => "ディスカウント ストア",
        "Suits Store" => "紳士服",
        "Christian Church" => "キリスト教協会",
        "Construction Company" => "建設会社",
        "Golf Driving Range" => "ゴルフ練習場",
        "Industrial Area" => "工業地帯",
        "Electronics Manufacturer" => "電子機器",
        "Shipping Company" => "運送会社",
        "Police Box" => "交番",
        "Baseball Field" => "野球場",
        "Newspaper Publisher" => "新聞社",
        "Vocational School" => "専門学校",
        "Outdoor Sports Store" => "アウトドア用品",
        "Driving School" => "自動車学校",
        "Renovation Contractor" => "リフォーム",
        "Instruction" => "専門学校",
        "Private University" => "私立大学",
        "Electronic Parts Supplier" => "電子部品",
        "Commercial Printer" => "印刷",
        "Event Venue" => "イベント会場",
        "Surgeon" => "外科",
        "Work Clothes Store" => "作業服",
        "Butsudan Store" => "仏壇",
        "Thrift Store" => "リサイクル",
        "Recording Studio" => "音楽スタジオ",
        "Trading Firm" => "商社",
        "Rental Meeting Room" => "レンタルルーム",
        "Building Materials Store" => "建材",
        "Luggage Store" => "かばん",
        "Tobacco Shop" => "タバコ",
        "Print Shop" => "印刷",
        "Computer Store" => "パソコン",
        "Bus Company" => "バス会社",
        "Software Company" => "ソフトウェア会社",
        "Gas Station" => "ガソリンスタンド",
        "Convenience Store" => "コンビニエンスストア",
        "Grocery Store" => "食料品店",
        "Parking Lot" => "駐車場",
        "restaurant" => "レストラン",
        "Supermarket" => "スーパー",
        "Post Office" => "郵便局",
    ],


    //TwitterReplyBot.phpで使用
    'BOT_REPLY_TWEET_CNT' => 2,
    'BOT_TARGET_PREF' => [
        "東京都",
    ],
    'BOT_TARGET_CAT' => ['restaurant', 'food', 'bakery', 'cafe'],
    'BOT_TARGET_KEYWORD' => [
        "グルメ",
        "おいし",
        "うまか",
        "うまい",
        "うます",
        "うまし",
        "美味",
        "デリシャス",
        "ボーノ",
        "ボーノ",
        "絶品",
        "ウマイ",
        "旨い",
        "旨か",
        "旨す",
        "旨し",
    ],

    'API_CNT' => 5,
    
    'JOGAI_TREND_NAME_PATTERN' => [
        '^入浴シーン$',
        '^スパイス$',
        '^タイムライン$',
        '^レギュラー$',
        '^ウインク$',
        '精子',
        'えっち',
        'すっぽんぽん',
        '^ファイナル$',
        '^ファンファーレ$',
        '美ボディ',
        '^ターン[0-9]$',
        '^受注.{0,3}$',
        '^.{0,3}路線$',
        '^.{0,3}登板$',
        '^.{0,3}抹消$',
        '^.{0,3}公開$',
        '^新作.{0,3}$',
        '割り込み',
        '水着カーマ',
        'カイニス',
        '中華BL',
        '誹謗',
        '批判',
        '中傷',
        '次世代MP5',
        "セクシー",
        "CHIMPO",
        "性器",
        "ノーブラ",
        "レイプ",
        'DLsite',
        '搾精研究所',
        'ニコニコ静画',
        '濡れ',
        '受け攻め',
        '深田えいみ',
        '奴隷',
        '裸',
        '癒し体験',
        '人妻',
        '黒ギャル',
        '^ホテル対応$',
        '猫又おかず',
        'リビドークロス',
        '私のとこ',
        '男性教師',
        'レーティング',
        '土曜出勤',
        '土砂降り',
        '土曜授業',
        'テスト最終日',
        '雨のせい',
        'ライブ配信',
        '全問正解',
        '連休',
        '休み',
        '公式マーク',
        '活動休止',
        'TP上昇',
        '公演中止',
        '最多更新',
        '勝ち点',
        '満塁',
        '[0-9]+連',
        '地方議員',
        '営業時間',
        '淫',
        '^コラボラジオlive$',
        '百合',
        '^ミーグリ$',
        '^フェロモン$',
        '^人身売買$',
        '^ジンチェンコ$',
        '^ロキシー$',
        '^時計回り$',
        '^提供画面$',
        '気温',
        '^審査員[a-zA-Z]$',
        '人気',
        '確定',
        '初回',
        'opなし',
        'op無し',
        '発表',
        '注意報',
        '警報',
        '合否',
        '選択',
        '検索',
        '全線',
        '五十音',
        '地方$',
        '[0-9][強弱]$',
        '確認',
        '確保',
        'の方$',
        '[0-9]割$',
        '出勤$',
        '表明$',
        '受け$',
        '決行$',
        '記事$',
        '主張$',
        '引退$',
        '率$',
        '違反$',
        '特典$',
        '会見$',
        '撤回$',
        '中止$',
        '延期$',
        '延長$',
        '検討$',
        '謝罪$',
        '相手$',
        '発言$',
        '通知$',
        '相手$',
        'OK$',
        'ＯＫ$',
        '新作$',
        '貸与$',
        '難易度$',
        '用語$',
        '気温$',
        '開催$',
        '会議$',
        '貸与$',
        '検討$',
        '^申し込み$',
        '^売り切れ$',
        '方針$',
        '報告$',
        '初日$',
        '割れ$',
        '傾向$',
        '検討$',
        '改定$',
        '改正$',
        '従業員$',
        '配置$',
        '移転$',
        '地方$',
        '^星[0-9]',
        '^全国最多$',
        '^Aパート$', 
        '^予約販売$',
        '^再販決定$',
        '^頼りがい$',
        '^開業延期$',
        '^海外選手$',
        '^状況次第$',
        '^映り込み$',
        '^浮き彫り$',
        '^追加発令$',
        '^記者会見$',
        '^提供開始$',
        '^最終調整$',
        '^すり抜け$',
        '^事前通販$',
        '^天気予報$',
        '^数カ月後$',
        '^日替わり$',
        '^舞台挨拶$',
        '^時間変更$',
        '^作業不備$',
        '^外交関係$',
        '^ストーブ$',
        '^マイナス$',
        '^期間途中$',
        '^ドッキリ$',
        '^続編決定$',
        '^正式表明$',
        '^写メ日記$',
        '^ジュリア$',
        '^水野さん$',
        '^軍事裁判$',
        '^シャトラ$',
        '^生田斗真$',
        '^牛柄ビキニ$',
        '^納得の大賞$',
        '^西暦の年と年齢$',
        'スケベ',
        'すけべ',
        '立ちんぼ',
        'っぱい',
        '里見ゆり',
        'セクシー女優',
        '一般',
        '鯖',
        'メンテ',
        '[A-ZＡ-Ｚ]カップ',
        '^次のプリキュア$',
        '^クロスアンジュ$',
        '^剣ちゃん$',
        '^白ギャル$',
        '^意外と純情$',
        '^サンタコス$',
        '^コミケ開催$',
        '^ファン感$',
        '^三木さん$',
        '^リサイクル$',
        '^女性活躍$',
        '^試合',
        '現役',
        '^鬼滅の刃実写化$',
        '^開かずの間$',
        '^エリアメール$',
        '^女装攻め$',
        '^練習試合$',
        '^国と地域$',
        '^連載再開$',
        '^ヤンチャ$',
        '^巻き込み$',
        '^エラー[0-9]$',
        '^おたえ誕生日$',
        '^柘植さん$',
        '^黒沢の妄想$',
        '^バスローブ$',
        '^オーラス$',
        '^ハンター$',
        '^スペース$',
        '^サッカー$',
        '^リサイクル$',
        '^ハギノアレグリアス$',
        '^こおわー$',
        '^Twitterの音$',
        '^アンジュ$',
        '^I字バランス$',
        '^国内大会$',
        '^ネクタイ$',
        '^サンプル$',
        '^グリーン$',
        'ほー$',
        '^全国放送$',
        '^兄弟替え玉$',
        '^たぬきの夢絵$',
        '^バチェロレッテ$',
        '^アニマル$',
        '^スポット$',
        '^メンタル$',
        '^ドライブ$',
        '^購入履歴$',
        '^スイッチ$',
        '^モニター$',
        '^スペック$',
        '^ローンチ$',
        '^ディスク$',
        '^勝ち越し$',
        '^自己採点$',
        '^東北地方$',
        '^休日出勤$',
        '^クラッシュ$',
        '^ランキング$',
        '^ランクイン$',
        '^エクササイズ$',
        '^スカサハ$',
        '^レオパルドン$',
        '^神ちゃん$',
        '^アズレン$',
        '^全年齢版$',
        '^キュアアース$',
        '^アルファタウリ$',
        '^モンツァ$',
        '^ランク[0-9]$',
        '^新キャラ$',
        '^valkyrie$',
        '^ソシエダ$',
        '^アイランド$',
        '^カレンダー$',
        '^年度始め$',
        '^電車普通$',
        '^ティッシュ$',
        '^新入社員$',
        '^経営会社$',
        '^サクセス$',
        '^コンビニ$',
        '^バイオリン$',
        '^スタメン$',
        '^クーラー$',
        '^オシャレ$',
        '^アイコン$',
        '^シーズン[0-9０-９]*$',
        "台風",
        "個人",
        "^TVCM第1弾$",
        "^キャスター$",
        "^フレンド$",
        "^トラック$",
        "^コーヒー$",
        "^マウンド$",
        "^スクイズ$",
        "^エアコン$",
        "^新人デビュー$",
        "^サイレン$",
        "^ウイルス$",
        "^オンライン$",
        "^予約完了$",
        "^注文完了$",
        "^試合中止$",
        "^ミニゲーム$",
        "^アンコール$",
        "^アクシデント$",
        "^スクラッチ$",
        "^転売OK$",
        "^アドレスバー$",
        "^アドバンテスト$",
        "^誤差なし$",
        "^アラーム$",
        "^タイブレーク$",
        "^テスト中$",
        "^入荷待ち$",
        "^トレンド$",
        "^好評配信中$",
        "^追加受付$",
        "^予測済み$",
        "^画像表示$",
        "^引き継ぎ$",
        "^続報中心$",
        "^ソフトメーカー$",
        "^打ち直し$",
        "ぱんつ",
        "パンツ",
        "鬼畜",
        "^FC動画$",
        "^キズナアイ$",
        "^千ちゃん$",
        "^池田エライザ$",
        "^Passion$",
        "^特異点F$",
        "SEX",
        "いじめ",
        "糞",
        "くそ",
        "クソ",
        "^特異点F$",
        "^マキオン$",
        "^origin$",
        "^SEKIROアプデ$",
        "^アーカイブ$",
        "^美月誕生日$",
        "^最上位のJK$",
        "^スコップ$",
        "^上下赤ジャージ$",
        "^鏡の国のアリス$",
        "^ステッカー$",
        "^郵送希望$",
        "^コールド$",
        "^感染拡大$",
        "^人身事故$",
        "^引き上げ$",
        "^アルバム$",
        "^ファンクラブ$",
        "^slave$",
        "^ジャンプ$",
        "^ブレイク$",
        "^良さそう$",
        "^トリック$",
        "^厳しすぎ$",
        "^お人好し$",
        "^店員さん$",
        "プレイ",
        "水着BB",
        "BBちゃん",
        "^スピード$",
        "臨時休校",
        "武蔵ちゃん",
        "ハイキュー",
        "パンイチ",
        "二階氏サイド",
        "長瀞さん",
        "プリコネアニメ",
        "水着アテナ",
        "インフルの新た",
        "コロナワクチン",
        "PUNPEE",
        "人魚の日",
        "コッコロママ",
        "引き分け",
        "テンション",
        "ネタバレ",
        "ホームラン",
        "首位",
        "ルーキー",
        "ヒット",
        "トレード",
        "リリース",
        "^スタンプ$",
        "百合の日",
        "KOD復活",
        "^性",
        "プリティフェイス",
        "ToLOVEる",
        "マジカミ",
        "全面解除",
        "相手女性",
        "多目的トイレ",
        "Dazzling White Town",
        "大捜査線",
        "大島さん",
        "上原亜衣",
        "LINE流出",
        "シックスナイン",
        "DMM",
        "レメリア",
        "dmm",
        "PSN障害",
        "ディオネ",
        "^ショック$",
        "^映画上映中$",
        "^Twitter開設$",
        "^心当たり$",
        "^カラオケ$",
        "^ノーカット$",
        "^スピーチ$",
        "^origin$",
        "^ラーメン$",
        "^ガイドブック$",
        "^グループ$",
        "地上波",
        "全員更新",
        "延期提案",
        "次の開催",
        "^私的利用$",
        "^スーパー$",
        "^タイミング$",
        "^キャンセル$",
        "^レストラン$",
        "^あと",
        "year[0-9]+",
        "人口の[0-9]+",
        "ベスト[0-9]+",
        "[0-9一二三]+[十百千万億兆]*[人点倍円年枚ド]",
        "[0-9一二三]+[十百千万億兆]",
        "懲役[0-9]+年",
        "[0-9一二三]+[位r％\%回話度]",
        "^[\+\.0-9]+$",
        "^basic$",
        "^story$",
        
        "動画配信者",
        "公開延期",
        "ユーザーID",
        "プレゼント",
        "午前",
        "午後",
        "史上",
        "過去",
        "勉強分野",
        "衝撃の",
        "海外進出",
        "画像付き",
        "異常気象",
        "メンバーカラー",
        "設営完了",
        "利下げ",
        "上げ幅",
        "下げ幅",
        "利上げ",
        "金利",
        "世界進出",
        "相互連番",
        "検討",
        "自粛",
        "制限",
        "下落",
        "季節外れ",
        "知事午後",
        "平均",
        "株価",
        "緊急",
        "全世界対象",
        "特別番組",
        "延期決定",
        "終値",
        "重大",
        "画質低下",
        "更新待ち",
        "世界最多",
        "新エリア",
        "営業禁止",
        "相場",
        "球児",
        "甲子園",
        "開始価格",
        "近所の声",
        "民間放出",
        "自動停止",
        "取引",
        "可能",
        "最悪の",
        "修正",
        "懸念",
        "伸び悩み",
        "大幅",
        "縮小",
        "撤退",
        "超過",
        "不安",
        
            "曜日",
            "ようび",
            "フォロ",
            "txt感",
            "メモメモ",
            "アルバム曲",
            "週の真ん中",
            "コメント",    
            "ツイート",    
            "公式Twitter",    
            "スタート",    
            "週の始まり",    
            "イベント",    
            "マグニチュード",    
            "津波",    
            "震度",    
            "地震",    
            "チケット",    
            "困惑と不安",    
            "アラート",    
            "ストレス",    
            "当たり前",    
            "イケメン",    
            "新フォーム",    
            "一挙放送",
            "遅刻遅刻",
            "ビックリ",
            "イメージ",
            "ニュース",
    ],

    'WOIED_ARR' => [
        //"Kitakyushu" => "1110809",
        //"Saitama" => "1116753",
        //"Chiba" => "1117034",
        //"Fukuoka" => "1117099",
        //"Hamamatsu" => "1117155",
        //"Hiroshima" => "1117227",
        //"Kawasaki" => "1117502",
        //"Kobe" => "1117545",
        //"Kumamoto" => "1117605",
        //"Nagoya" => "1117817",
        //"Niigata" => "1117881",
        //"Sagamihara" => "1118072",
        //"Sapporo" => "1118108",
        //"Sendai" => "1118129",
        //"Takamatsu" => "1118285",
        "Tokyo" => "1118370",
        //"Yokohama" => "1118550",
        //"Okinawa" => "2345896",
        "Osaka" => "15015370",
        //"Kyoto" => "15015372",
        //"Okayama" => "90036018",
        "Japan" => "23424856",
    ],


];