<?php

return [
    'TWITTER_CLIENT_KEY' => env('TWITTER_CLIENT_KEY', ''),
    'TWITTER_CLIENT_SECRET' => env('TWITTER_CLIENT_SECRET', ''),
    'TWITTER_CLIENT_ID_ACCESS_TOKEN' => env('TWITTER_CLIENT_ID_ACCESS_TOKEN', ''),
    'TWITTER_CLIENT_ID_ACCESS_TOKEN_SECRET' => env('TWITTER_CLIENT_ID_ACCESS_TOKEN_SECRET', ''),
    'TWITTER_CALLBACK_URL' => env('TWITTER_CALLBACK_URL', ''),
];